import { CORPS, DEXTERITE, EMPATHIE, INTELLIGENCE, REFLEXES, TECHNIQUE, VOLONTE } from "./caracteristiques-fake";
import { ARTISAN, BARDE, CRIMINEL, DOCTEUR, HOMME_D_ARME, MAGE, MARCHAND, NOBLE, PRETRE, SORCELEUR } from "./profession-fake";

export const COMPETENCE_LIST = [
    { idCompetence: 1,  nom: "Adresse", description: "Capacité à viser juste", isExclusif: false, caracteristique: DEXTERITE },
    { idCompetence: 2,  nom: "Alchimie", description: "Capacité à créer des potions", isExclusif: false, caracteristique: TECHNIQUE },
    { idCompetence: 3,  nom: "Arbalète", description: "Capacité à utiliser une arbalète", isExclusif: false, caracteristique: DEXTERITE },
    { idCompetence: 4,  nom: "Aracherie", description: "Capacité à utiliser un arc", isExclusif: false, caracteristique: DEXTERITE, tag: "homme d'arme, noble" },
    { idCompetence: 5,  nom: "Artisanat", description: "Capacité à fabriquer des objets", isExclusif: false, caracteristique: TECHNIQUE },
    { idCompetence: 6,  nom: "Athlétisme", description: "Capacité à sauter et à courir", isExclusif: false, caracteristique: DEXTERITE, tag: "homme d'armenoble" },
    { idCompetence: 7,  nom: "Bagarre", description: "Capacité à se battre au corps à corps", isExclusif: false, caracteristique: REFLEXES, tag: "homme d'armenoble" }, 
    { idCompetence: 8,  nom: "Bâton/Lance", description: "Capacité à utiliser un bâton ou une lance", isExclusif: false, caracteristique: REFLEXES, tag: "homme d'armenoble" },
    { idCompetence: 9,  nom: "Beaux-arts", description: "Capacité à créer des œuvres d'art", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 10, nom: "Charisme", description: "Capacité à influencer les autres", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 11, nom: "Commandement", description: "Capacité à diriger des troupes", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 12, nom: "Connaissance de la rue", description: "Connaissance des bas-fonds", isExclusif: false, caracteristique: INTELLIGENCE },
    { idCompetence: 13, nom: "Connaissance des monstres", description: "Connaissance des créatures surnaturelles", isExclusif: false, caracteristique: INTELLIGENCE },
    { idCompetence: 14, nom: "Contrefaçon", description: "Capacité à imiter des documents", isExclusif: false, caracteristique: TECHNIQUE },
    { idCompetence: 15, nom: "Courage", description: "Capacité à ne pas fuir", isExclusif: false, caracteristique: VOLONTE },
    { idCompetence: 16, nom: "Crochetage", description: "Capacité à ouvrir des serrures", isExclusif: false, caracteristique: TECHNIQUE },
    { idCompetence: 17, nom: "Déduction", description: "Capacité à résoudre des énigmes", isExclusif: false, caracteristique: INTELLIGENCE },
    { idCompetence: 18, nom: "Déguisement", description: "Capacité à se déguiser", isExclusif: false, caracteristique: TECHNIQUE },
    { idCompetence: 19, nom: "Duperie", description: "Capacité à mentir", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 20, nom: "Éducation", description: "Capacité à apprendre", isExclusif: false, caracteristique: INTELLIGENCE },
    { idCompetence: 21, nom: "Enseignement", description: "Capacité à enseigner", isExclusif: false, caracteristique: INTELLIGENCE },
    { idCompetence: 22, nom: "Envoûtement", description: "Capacité à lancer des sorts", isExclusif: false, caracteristique: VOLONTE },
    { idCompetence: 23, nom: "Équitation", description: "Capacité à monter à cheval", isExclusif: false, caracteristique: REFLEXES },
    { idCompetence: 24, nom: "Escrime", description: "Capacité à manier l'épée", isExclusif: false, caracteristique: REFLEXES, tag: "homme d'armenoble" },
    { idCompetence: 25, nom: "Esquive/Évasion", description: "Capacité à éviter les attaques", isExclusif: false, caracteristique: REFLEXES },
    { idCompetence: 26, nom: "Étiquette", description: "Connaissance des usages sociaux", isExclusif: false, caracteristique: INTELLIGENCE },
    { idCompetence: 27, nom: "Fabrication de piège", description: "Capacité à créer des pièges", isExclusif: false, caracteristique: TECHNIQUE },
    { idCompetence: 28, nom: "Furtivité", description: "Capacité à se cacher", isExclusif: false, caracteristique: DEXTERITE },
    { idCompetence: 29, nom: "Incantation", description: "Capacité à lancer des sorts", isExclusif: false, caracteristique: VOLONTE },
    { idCompetence: 30, nom: "Intimidation", description: "Capacité à effrayer les autres", isExclusif: false, caracteristique: VOLONTE },
    { idCompetence: 31, nom: "Jeu", description: "Capacité à jouer", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 32, nom: "Langue ancienne", description: "Connaissance des langues anciennes", isExclusif: false, caracteristique: INTELLIGENCE, tag: "bardemarchand" },
    { idCompetence: 33, nom: "Langue commune", description: "Connaissance de la langue commune", isExclusif: false, caracteristique: INTELLIGENCE, tag: "bardemarchand" },
    { idCompetence: 34, nom: "Langue naine", description: "Connaissance de la langue naine", isExclusif: false, caracteristique: INTELLIGENCE, tag: "bardemarchand" },
    { idCompetence: 35, nom: "Lame courte", description: "Capacité à manier la dague", isExclusif: false, caracteristique: REFLEXES, tag: "homme d'armenoble" },
    { idCompetence: 36, nom: "Mêlée", description: "Capacité à se battre au corps à corps", isExclusif: false, caracteristique: REFLEXES, tag: "homme d'armenoble" },
    { idCompetence: 37, nom: "Navigation", description: "Capacité à se repérer", isExclusif: false, caracteristique: REFLEXES },
    { idCompetence: 38, nom: "Négoce", description: "Capacité à commercer", isExclusif: false, caracteristique: INTELLIGENCE },
    { idCompetence: 39, nom: "Persuasion", description: "Capacité à convaincre", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 40, nom: "Physique", description: "Capacité à soulever des charges", isExclusif: false, caracteristique: CORPS },
    { idCompetence: 41, nom: "Premiers soins", description: "Capacité à soigner", isExclusif: false, caracteristique: TECHNIQUE },
    { idCompetence: 42, nom: "Psychologie", description: "Capacité à comprendre les autres", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 43, nom: "Résilience", description: "Capacité à encaisser les coups", isExclusif: false, caracteristique: CORPS },
    { idCompetence: 44, nom: "Représentation", description: "Capacité à jouer la comédie", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 45, nom: "Résistance à la contrainte", description: "Capacité à résister à la torture", isExclusif: false, caracteristique: VOLONTE },
    { idCompetence: 46, nom: "Résistance à la magie", description: "Capacité à résister aux sorts", isExclusif: false, caracteristique: VOLONTE },
    { idCompetence: 47, nom: "Rituels", description: "Capacité à lancer des sorts", isExclusif: false, caracteristique: VOLONTE },
    { idCompetence: 48, nom: "Séduction", description: "Capacité à charmer", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 49, nom: "Stylisme", description: "Capacité à s'habiller", isExclusif: false, caracteristique: EMPATHIE },
    { idCompetence: 50, nom: "Survie", description: "Capacité à survivre en milieu hostile", isExclusif: false, caracteristique: INTELLIGENCE },
    { idCompetence: 51, nom: "Tactique", description: "Capacité à diriger des troupes", isExclusif: false, caracteristique: INTELLIGENCE, tag: "homme d'armenoble" },
    { idCompetence: 52, nom: "Vigilance", description: "Capacité à repérer les dangers", isExclusif: false, caracteristique: INTELLIGENCE },

    { idCompetence: 53, nom: "Rafistolage", description: "Capacité à réparer des objets", isExclusif: true, caracteristique: TECHNIQUE },
    { idCompetence: 54, nom: "Prestation", description: "Capacité à réaliser des prestations", isExclusif: true, caracteristique: EMPATHIE },
    { idCompetence: 55, nom: "Paranaïa exercée", description: "Capacité à exercer la paranoïa", isExclusif: true, caracteristique: INTELLIGENCE },
    { idCompetence: 56, nom: "Main thérapeutique", description: "Capacité à soigner par le toucher", isExclusif: true, caracteristique: EMPATHIE },
    { idCompetence: 57, nom: "Dur à cuire", description: "Capacité à encaissser les coups", isExclusif: true, caracteristique: CORPS },
    { idCompetence: 58, nom: "Exercice de la magie", description: "Capacité à lancer des sorts", isExclusif: true, caracteristique: INTELLIGENCE },
    { idCompetence: 59, nom: "Grand voyageur", description: "Capacité à voyager", isExclusif: true, caracteristique: INTELLIGENCE },
    { idCompetence: 60, nom: "Initié des dieux", description: "Capacité à invoquer les dieux", isExclusif: true, caracteristique: EMPATHIE },
    { idCompetence: 61, nom: "formation de sorceleur", description: "Capacité à former des sorceleurs", isExclusif: true, caracteristique: INTELLIGENCE },
    { idCompetence: 62, nom: "Prestige", description: "Capacité à influencer les autres", isExclusif: true },
]