import { CORPS, DEXTERITE, EMPATHIE, INTELLIGENCE, REFLEXES, TECHNIQUE, VOLONTE } from "./caracteristiques-fake";
import { ARTISAN, BARDE, CRIMINEL, DOCTEUR, HOMME_D_ARME, MAGE, MARCHAND, NOBLE, PRETRE, SORCELEUR } from "./profession-fake";

export const COMPETENCE_LIST = [
    { idCompetence: 1,  nom: "Adresse", description: "Capacité à viser juste", exclusif: false, caracteristique: DEXTERITE, professions: [CRIMINEL] },
    { idCompetence: 2,  nom: "Alchimie", description: "Capacité à créer des potions", exclusif: false, caracteristique: TECHNIQUE, professions: [ARTISAN, DOCTEUR, SORCELEUR] },
    { idCompetence: 3,  nom: "Arbalète", description: "Capacité à utiliser une arbalète", exclusif: false, caracteristique: DEXTERITE, professions: [] },
    { idCompetence: 4,  nom: "Aracherie", description: "Capacité à utiliser un arc", exclusif: false, caracteristique: DEXTERITE, professions: [], tag: ["homme d'arme", "noble"] },
    { idCompetence: 5,  nom: "Artisanat", description: "Capacité à fabriquer des objets", exclusif: false, caracteristique: TECHNIQUE, professions: [ARTISAN] },
    { idCompetence: 6,  nom: "Athlétisme", description: "Capacité à sauter et à courir", exclusif: false, caracteristique: DEXTERITE, professions: [ARTISAN, CRIMINEL, SORCELEUR], tag: ["homme d'arme", "noble"] },
    { idCompetence: 7,  nom: "Bagarre", description: "Capacité à se battre au corps à corps", exclusif: false, caracteristique: REFLEXES, professions: [], tag: ["homme d'arme", "noble"] }, 
    { idCompetence: 8,  nom: "Bâton/Lance", description: "Capacité à utiliser un bâton ou une lance", exclusif: false, caracteristique: REFLEXES, professions: [MAGE], tag: ["homme d'arme", "noble"] },
    { idCompetence: 9,  nom: "Beaux-arts", description: "Capacité à créer des œuvres d'art", exclusif: false, caracteristique: EMPATHIE, professions: [ARTISAN, BARDE] },
    { idCompetence: 10, nom: "Charisme", description: "Capacité à influencer les autres", exclusif: false, caracteristique: EMPATHIE, professions: [BARDE, DOCTEUR, MARCHAND, PRETRE] },
    { idCompetence: 11, nom: "Commandement", description: "Capacité à diriger des troupes", exclusif: false, caracteristique: EMPATHIE, professions: [PRETRE, NOBLE] },
    { idCompetence: 12, nom: "Connaissance de la rue", description: "Connaissance des bas-fonds", exclusif: false, caracteristique: INTELLIGENCE, professions: [ARTISAN, BARDE, CRIMINEL, MARCHAND] },
    { idCompetence: 13, nom: "Connaissance des monstres", description: "Connaissance des créatures surnaturelles", exclusif: false, caracteristique: INTELLIGENCE, professions: [] },
    { idCompetence: 14, nom: "Contrefaçon", description: "Capacité à imiter des documents", exclusif: false, caracteristique: TECHNIQUE, professions: [CRIMINEL] },
    { idCompetence: 15, nom: "Courage", description: "Capacité à ne pas fuir", exclusif: false, caracteristique: VOLONTE, professions: [DOCTEUR, HOMME_D_ARME, PRETRE] },
    { idCompetence: 16, nom: "Crochetage", description: "Capacité à ouvrir des serrures", exclusif: false, caracteristique: TECHNIQUE, professions: [CRIMINEL] },
    { idCompetence: 17, nom: "Déduction", description: "Capacité à résoudre des énigmes", exclusif: false, caracteristique: INTELLIGENCE, professions: [DOCTEUR, SORCELEUR] },
    { idCompetence: 18, nom: "Déguisement", description: "Capacité à se déguiser", exclusif: false, caracteristique: TECHNIQUE, professions: [] },
    { idCompetence: 19, nom: "Duperie", description: "Capacité à mentir", exclusif: false, caracteristique: EMPATHIE, professions: [BARDE, CRIMINEL, NOBLE] },
    { idCompetence: 20, nom: "Éducation", description: "Capacité à apprendre", exclusif: false, caracteristique: INTELLIGENCE, professions: [ARTISAN, MAGE, MARCHAND, NOBLE] },
    { idCompetence: 21, nom: "Enseignement", description: "Capacité à enseigner", exclusif: false, caracteristique: INTELLIGENCE, professions: [PRETRE] },
    { idCompetence: 22, nom: "Envoûtement", description: "Capacité à lancer des sorts", exclusif: false, caracteristique: VOLONTE, professions: [MAGE, PRETRE] },
    { idCompetence: 23, nom: "Équitation", description: "Capacité à monter à cheval", exclusif: false, caracteristique: REFLEXES, professions: [SORCELEUR, NOBLE] },
    { idCompetence: 24, nom: "Escrime", description: "Capacité à manier l'épée", exclusif: false, caracteristique: REFLEXES, professions: [SORCELEUR], tag: ["homme d'arme", "noble"] },
    { idCompetence: 25, nom: "Esquive/Évasion", description: "Capacité à éviter les attaques", exclusif: false, caracteristique: REFLEXES, professions: [HOMME_D_ARME, SORCELEUR] },
    { idCompetence: 26, nom: "Étiquette", description: "Connaissance des usages sociaux", exclusif: false, caracteristique: INTELLIGENCE, professions: [BARDE, DOCTEUR, MAGE, NOBLE] },
    { idCompetence: 27, nom: "Fabrication de piège", description: "Capacité à créer des pièges", exclusif: false, caracteristique: TECHNIQUE, professions: [] },
    { idCompetence: 28, nom: "Furtivité", description: "Capacité à se cacher", exclusif: false, caracteristique: DEXTERITE, professions: [CRIMINEL, SORCELEUR] },
    { idCompetence: 29, nom: "Incantation", description: "Capacité à lancer des sorts", exclusif: false, caracteristique: VOLONTE, professions: [MAGE, PRETRE, SORCELEUR] },
    { idCompetence: 30, nom: "Intimidation", description: "Capacité à effrayer les autres", exclusif: false, caracteristique: VOLONTE, professions: [HOMME_D_ARME] },
    { idCompetence: 31, nom: "Jeu", description: "Capacité à jouer", exclusif: false, caracteristique: EMPATHIE, professions: [CRIMINEL, MARCHAND] },
    { idCompetence: 32, nom: "Langue ancienne", description: "Connaissance des langues anciennes", exclusif: false, caracteristique: INTELLIGENCE, professions: [], tag: ["barde", "marchand"] },
    { idCompetence: 33, nom: "Langue commune", description: "Connaissance de la langue commune", exclusif: false, caracteristique: INTELLIGENCE, professions: [], tag: ["barde", "marchand"] },
    { idCompetence: 34, nom: "Langue naine", description: "Connaissance de la langue naine", exclusif: false, caracteristique: INTELLIGENCE, professions: [], tag: ["barde", "marchand"] },
    { idCompetence: 35, nom: "Lame courte", description: "Capacité à manier la dague", exclusif: false, caracteristique: REFLEXES, professions: [CRIMINEL, DOCTEUR, MARCHAND], tag: ["homme d'arme", "noble"] },
    { idCompetence: 36, nom: "Mêlée", description: "Capacité à se battre au corps à corps", exclusif: false, caracteristique: REFLEXES, professions: [], tag: ["homme d'arme", "noble"] },
    { idCompetence: 37, nom: "Navigation", description: "Capacité à se repérer", exclusif: false, caracteristique: REFLEXES, professions: [] },
    { idCompetence: 38, nom: "Négoce", description: "Capacité à commercer", exclusif: false, caracteristique: INTELLIGENCE, professions: [ARTISAN, DOCTEUR, MARCHAND] },
    { idCompetence: 39, nom: "Persuasion", description: "Capacité à convaincre", exclusif: false, caracteristique: EMPATHIE, professions: [ARTISAN, BARDE, MARCHAND, NOBLE] },
    { idCompetence: 40, nom: "Physique", description: "Capacité à soulever des charges", exclusif: false, caracteristique: CORPS, professions: [ARTISAN, HOMME_D_ARME] },
    { idCompetence: 41, nom: "Premiers soins", description: "Capacité à soigner", exclusif: false, caracteristique: TECHNIQUE, professions: [PRETRE] },
    { idCompetence: 42, nom: "Psychologie", description: "Capacité à comprendre les autres", exclusif: false, caracteristique: EMPATHIE, professions: [BARDE, DOCTEUR, MAGE, MARCHAND, PRETRE, NOBLE] },
    { idCompetence: 43, nom: "Résilience", description: "Capacité à encaisser les coups", exclusif: false, caracteristique: CORPS, professions: [ARTISAN] },
    { idCompetence: 44, nom: "Représentation", description: "Capacité à jouer la comédie", exclusif: false, caracteristique: EMPATHIE, professions: [BARDE] },
    { idCompetence: 45, nom: "Résistance à la contrainte", description: "Capacité à résister à la torture", exclusif: false, caracteristique: VOLONTE, professions: [DOCTEUR, MARCHAND] },
    { idCompetence: 46, nom: "Résistance à la magie", description: "Capacité à résister aux sorts", exclusif: false, caracteristique: VOLONTE, professions: [MAGE] },
    { idCompetence: 47, nom: "Rituels", description: "Capacité à lancer des sorts", exclusif: false, caracteristique: VOLONTE, professions: [MAGE, PRETRE] },
    { idCompetence: 48, nom: "Séduction", description: "Capacité à charmer", exclusif: false, caracteristique: EMPATHIE, professions: [BARDE,MAGE] },
    { idCompetence: 49, nom: "Stylisme", description: "Capacité à s'habiller", exclusif: false, caracteristique: EMPATHIE, professions: [MAGE, NOBLE] },
    { idCompetence: 50, nom: "Survie", description: "Capacité à survivre en milieu hostile", exclusif: false, caracteristique: INTELLIGENCE, professions: [DOCTEUR, HOMME_D_ARME, PRETRE, SORCELEUR] },
    { idCompetence: 51, nom: "Tactique", description: "Capacité à diriger des troupes", exclusif: false, caracteristique: INTELLIGENCE, professions: [], tag: ["homme d'arme", "noble"] },
    { idCompetence: 52, nom: "Vigilance", description: "Capacité à repérer les dangers", exclusif: false, caracteristique: INTELLIGENCE, professions: [CRIMINEL, SORCELEUR, NOBLE] },

    { idCompetence: 53, nom: "Rafistolage", description: "Capacité à réparer des objets", exclusif: true, caracteristique: TECHNIQUE, professions: [ARTISAN] },
    { idCompetence: 54, nom: "Prestation", description: "Capacité à réaliser des prestations", exclusif: true, caracteristique: EMPATHIE, professions: [BARDE] },
    { idCompetence: 55, nom: "Paranaïa exercée", description: "Capacité à exercer la paranoïa", exclusif: true, caracteristique: INTELLIGENCE, professions: [CRIMINEL] },
    { idCompetence: 56, nom: "Main thérapeutique", description: "Capacité à soigner par le toucher", exclusif: true, caracteristique: EMPATHIE, professions: [DOCTEUR] },
    { idCompetence: 57, nom: "Dur à cuire", description: "Capacité à encaissser les coups", exclusif: true, caracteristique: CORPS, professions: [HOMME_D_ARME] },
    { idCompetence: 58, nom: "Exercice de la magie", description: "Capacité à lancer des sorts", exclusif: true, caracteristique: INTELLIGENCE, professions: [MAGE] },
    { idCompetence: 59, nom: "Grand voyageur", description: "Capacité à voyager", exclusif: true, caracteristique: INTELLIGENCE, professions: [MARCHAND] },
    { idCompetence: 60, nom: "Initié des dieux", description: "Capacité à invoquer les dieux", exclusif: true, caracteristique: EMPATHIE, professions: [PRETRE] },
    { idCompetence: 61, nom: "formation de sorceleur", description: "Capacité à former des sorceleurs", exclusif: true, caracteristique: INTELLIGENCE, professions: [SORCELEUR] },
    { idCompetence: 62, nom: "Prestige", description: "Capacité à influencer les autres", exclusif: true, professions: [NOBLE] },
]