import { Magie, MagieList } from "../models/magie";

export const MAGIE_LIST: MagieList = [
    { idMagie: 1, nom: "Compas magique", cout: "3 END", effet: "Le compas magique permet de déterminer instantanément la direction vers un endroit où vous êtes déjà allée auparavant. Sinon, le sort indique le nord.",portee: "Personnelle", duree: "1D6 heure", nature: "Terre", type: "Sorts", niveau: "Novice", contre: ""},
    { idMagie: 2, nom: "Dissipation", cout: "Variable", effet: "Dissipation met fin à un sort, un rituel ou une malédiction en cours dans sa portée. Ce sort permet d'abbuler une magie qui dure et peut être utilisé comme une action défensive pour bloquer une attaque magique avec ou sans composants. Pour annuler un effet magique, vous devez dépenser la moitié des points de Résilience utilisés par le lanceur et réussir un jet d'Incantation en opposition à son jet pour lancer le sort.",portee: "10 m", duree: "Instantané", nature: "Feu", type: "Sorts", niveau: "Novice", contre: "Incantation"},
    { idMagie: 3, nom: "Glamour", cout: "5 END", effet: "Glamour vous permet de mettre une illusion autour de vous qui vous fait paraître éblouissant. Ce sort vous donne un bonus de +3 en Séduction, Charisme et Commandement.",portee: "Personnelle", duree: "1D6 heure", nature: "Terre", type: "Sorts", niveau: "Novice", contre: ""},
    { idMagie: 4, nom: "Invocation de bâton", cout: "2 END", effet: "Invocation de bâton vous permet de dématérialiser votre bâton et de le téléporter à un endroit où vous avez été présent au cours du dernier jour. Vous pouvez lancer à nouveau le sort pour faire revenir le bâton à vous.",portee: "", duree: "Instantané", nature: "Feu", type: "Sorts", niveau: "Novice", contre: ""},
    { idMagie: 5, nom: "Manipulation de l'esprit", cout: "3 END", effet: "Manipulation de l'esprit vous permet de forcer votre cible à ressentir l'une de ces émotions pendant la durée du sort : haine, amour, dépression ou euphorie.",portee: "5 m", duree: "1D10 rounds", nature: "Terre", type: "Sorts", niveau: "Novice", contre: "Résistance à la magie"},
    { idMagie: 6, nom: "Miroir d'Afan", cout: "3 END", effet: "Inventé par le talentueux magicien aedirnien Afan de Guletta, le miroir d'Afan crée 1D10 copies illusoires du lanceur. Ces popies sont intangibles, mais impossibles à différencier du lanceur, qui les contrôle par l'esprit. Contrôler ces copies ne demande pas d'action, mais elles ne peuvent pas se déplacer au-delà de la portée du dort.",portee: "10 m", duree: "Actif (2 END", nature: "Eau", type: "Sorts", niveau: "Novice", contre: ""},
    { idMagie: 7, nom: "Poussière aveuglante", cout: "3 END", effet: "La poussière aveuglante vous permet de lancer une poussière magique dans les yeux d'une cible afin de l'aveugler pour la durée du sort.",portee: "4 m", duree: "1D10 rounds", nature: "Eau", type: "Sorts", niveau: "Novice", contre: "Esquive ou Blocage"},
    { idMagie: 8, nom: "Illusion", cout: "8 END", effet: "Lorem ipsum dolor",portee: "", duree: "20 m", nature: "Eau", type: "Sorts", niveau: "Compagnon", contre: "Résistance à la magie"},
    { idMagie: 9, nom: "Fils de vie", cout: "1 END", effet: "Lorem ipsum dolor",portee: "personelle", duree: "1D6 round", nature: "Eau",type: "Invocation",  niveau: "Novice", contre: ""},
    { idMagie: 11, nom: "Réservoir primal", cout: "1 END", effet: "Lorem ipsum dolor",portee: "personelle", duree: "1D6 round", nature: "Feu", type: "Invocation",  niveau: "Compagnon", contre: ""},
    { idMagie: 12, nom: "Chant céleste", cout: "1 END", effet: "Lorem ipsum dolor",portee: "personelle", duree: "1D6 round", nature: "Feu", type: "Invocation",  niveau: "Novice", contre: ""},
    { idMagie: 13, nom: "Averse", cout: "1 END", effet: "Lorem ipsum dolor",portee: "personelle", duree: "1D6 round", nature: "Air", type: "Invocation",  niveau: "Novice", contre: ""},
    { idMagie: 14, nom: "Yrden", cout: "1 END", effet: "Lorem ipsum dolor",portee: "personelle", duree: "1D6 round", nature: "Air", type: "Signe",  niveau: "Basique", contre: ""},
    { idMagie: 15, nom: "Quen", cout: "1 END", effet: "Lorem ipsum dolor",portee: "personelle", duree: "1D6 round", nature: "Feu", type: "Signe",  niveau: "Basique", contre: ""},
    { idMagie: 16, nom: "Aard", cout: "1 END", effet: "Lorem ipsum dolor",portee: "personelle", duree: "1D6 round", nature: "Mixte", type: "Signe",  niveau: "Basique", contre: ""},
    { idMagie: 17, nom: "Igni", cout: "1 END", effet: "Lorem ipsum dolor",portee: "personelle", duree: "1D6 round", nature: "Mixte", type: "Signe",  niveau: "Basique", contre: ""},
    { idMagie: 18, nom: "Axii", cout: "1 END", effet: "Lorem ipsum dolor",portee: "personelle", duree: "1D6 round", nature: "Mixte", type: "Signe",  niveau: "Basique", contre: ""}
]
