import { RituelList } from "../models/rituel";

export const RITUEL_LIST: RituelList = [
    { idRituel: 1, nom: "Hydromancie", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité d'eau ou un bol d'eau, 1 éclar de lune, 1 goutte de sang", niveau: "novice" },
    { idRituel: 2, nom: "Pyromancie", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité de feu ou un bol de feu, 1 éclar de lune, 1 goutte de sang", niveau: "novice" },
    { idRituel: 3, nom: "Terre et Pierre", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité de terre ou un bol de terre, 1 éclar de lune, 1 goutte de sang", niveau: "novice" },
    { idRituel: 4, nom: "Aérien", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité d'air ou un bol d'air, 1 éclar de lune, 1 goutte de sang", niveau: "novice" },
    { idRituel: 5, nom: "Mélange", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité de mélange ou un bol de mélange, 1 éclar de lune, 1 goutte de sang", niveau: "novice" },
    { idRituel: 6, nom: "Eau et Feu", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité d'eau et de feu ou un bol d'eau et de feu, 1 éclar de lune, 1 goutte de sang", niveau: "novice" },
    { idRituel: 7, nom: "Terre et Air", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité de terre et d'air ou un bol de terre et d'air, 1 éclar de lune, 1 goutte de sang", niveau: "compagnon" },
    { idRituel: 8, nom: "Eau et Terre", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité d'eau et de terre ou un bol d'eau et de terre, 1 éclar de lune, 1 goutte de sang", niveau: "compagnon" },
    { idRituel: 9, nom: "Feu et Air", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité de feu et d'air ou un bol de feu et d'air, 1 éclar de lune, 1 goutte de sang", niveau: "Maître" },
    { idRituel: 10, nom: "Eau et Air", cout: "5 END", effet: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", tempPreparation: "5 rounds", sd: "15 (18)", duree: "actif (2END)", composant: "une petite quantité d'eau et d'air ou un bol d'eau et d'air, 1 éclar de lune, 1 goutte de sang", niveau: "Maître" },


]